// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVWhIkzcIUxbarQxqaxOPHZaslMI_iqJ4',
    appId: '1:281808901895:web:d39395ecea956face6d7a2',
    messagingSenderId: '281808901895',
    projectId: 'jobfe-a636f',
    authDomain: 'jobfe-a636f.firebaseapp.com',
    storageBucket: 'jobfe-a636f.appspot.com',
    measurementId: 'G-5F1WYQSXZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACH2--oMRDHXumMYuwt14Yk2QsODFO8UM',
    appId: '1:281808901895:android:a50571e6bf5a4867e6d7a2',
    messagingSenderId: '281808901895',
    projectId: 'jobfe-a636f',
    storageBucket: 'jobfe-a636f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvRaOgT4L9gcRvf_ZGWuy5bN-oJmL1Q9M',
    appId: '1:281808901895:ios:bbc8094305398e10e6d7a2',
    messagingSenderId: '281808901895',
    projectId: 'jobfe-a636f',
    storageBucket: 'jobfe-a636f.appspot.com',
    iosClientId: '281808901895-o7qufd085ogbj91l6durrdoiolq4gcg7.apps.googleusercontent.com',
    iosBundleId: 'com.hires.app',
  );
}
